### ISSUE TITLE
No module named 'ip_basic'

### ISSUE THREAD

**Issue by BIurryface** [kujason/ip_basic#10]
I follow the Setup but end up with [ModuleNotFoundError: No module named 'ip_basic'].
How can I solve this problem and run the code?
Waiting for ur reply, thx

**Comment by kujason** [comment]
Are you running the demo from the top level using `python3 demos/depth_completion.py`? If that does not work, you may need to add the cloned folder to your `PYTHONPATH`.

**Comment by midnightluo** [comment]
Hello, I have the same problem here, but I am already to add the cloned folder to my PYTHONPATH.
PYTHONPATH=/home/trywait/ip_basic/ip_basic
another question is about the dataset , data_depth_velodyne.zip and data_depth_annotated.zip both include 'train' and 'val' folder, which one should I unzip and use  it?
waiting for your reply , thank you very much.
