### ISSUE TITLE
What is the noise removal algorithm used in your youtube video? 

### ISSUE THREAD

**Issue by placeforyiming** [kujason/ip_basic#11]
Thanks for your great idea!

Could you tell me what is the noise removal algorithm showed in the youtube video? (The right sample in the second row)
https://www.youtube.com/watch?v=t_CGGUE2kEM&t=3s&ab_channel=WAVELaboratory

Thanks!

**Comment by kujason** [comment]
The "noise removal" just refers to the extra median blur operation which is helpful in removing some of the outlier depth values in the scene. You can try it by setting `fill_type = 'multiscale'` in the demo.

**Comment by placeforyiming** [comment]
Thanks!
