### ISSUE TITLE
How to convert velo to depth_map, so I can use ip-basic.

### ISSUE THREAD

**Issue by Senwang98** [kujason/ip_basic#12]
@kujason 
Hi, I am trying to using your repo.
I found that the IP_basic accept .png file.
How to using .bin file by ip-basic? (Or, can you help me convert velo into depth-map? thanks)

**Comment by kujason** [comment]
Hi there, to convert a point cloud to depth map, you can use the projection
function in
https://github.com/kujason/scene_vis/blob/4d6adc61fd373d8e9b15a5e24f46420685393632/src/core/depth_map_utils.py#L113
And save the depth map to a png file.

To read a bin file, you can try something like this:
https://github.com/kujason/wavedata/blob/c4b5aabd9eb3b74fad777349f75161032d3460fa/wavedata/tools/core/calib_utils.py#L353

**Comment by Senwang98** [comment]
@kujason 
Thanks, I will try it.

**Comment by zijianh4** [comment]
> @kujason
> Thanks, I will try it.

Hi @Senwang98 and @kujason  ,
Have you solved the problem? I am also trying toconvert velo to depth_map with KITTI data. Currently, I multiply the Tr_velo_to_cam and  the raw velodyne file to get the point cloud in cam0 coordinate, and multiply the P2 and R0_rect to serve as the projection matrix. However, after I feed these two values and also the image size which is [512, 1382] in KITTI dataset, I only get nearly all zero matrix. Could you help me? Thanks! :)
