### ISSUE TITLE
My output folder is empty

### ISSUE THREAD

**Issue by midnightluo** [kujason/ip_basic#13]
I'm already run this demo with zero error and  get the output, but I dont know why my output folder is empty, the Kitti folder is organized as yours. waiting for your reply  and really thank u.

**Comment by 1gjjuser1** [comment]
I also encountered this problem, have you solved it?

**Comment by IoannaB04** [comment]
In case anyone has the same problem, here is what I did to fix it:

1. delete the file intrinsics from directories:
	test_depth_completion_anonymous
	test_depth_prediction_anonymous
	val_selection_cropped

2. if you are using windows, the kitti dataset should be in the path:` C:\Users\your_user_name\Kitti` ...

3. you should replace / (Linux) with \ (windows). Here is a code that does it for you. You have to create a new dummy .py in demos directory and write
		
```
with open("depth_completion.py", "r") as file:
    code = file.read()

code = code.replace('/', '\')

with open("depth_completion.py", "r") as file:
    code = file.read()
    exec(code)
```


Keep in mind that each time you run depth_completion.py a new directory will be created in outputs.

**Comment by midnightluo** [comment]
Hi, Sorry for this late. I almost forgot the problem of how I met exactly, So I don't remember the details, but I guess maybe you didn't set your 'output folder’ path correctly. Check the image I've loaded. I hope this can help you.


&nbsp; &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kujason/ip_basic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 晚上6:30
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [kujason/ip_basic] My output folder is empty (Issue #13)





 
Hello, I have the same problem. I see that you closed the issue so I guess you found the solution. Could you please share it?
