### ISSUE TITLE
How does this solution perform on lower-beam lidars?

### ISSUE THREAD

**Issue by mac137** [kujason/ip_basic#8]
Hello! As in the topic. Could anyone, please, tell me how this solution performs on lower-beam lidars, especially 16-beam Velodyne?

**Comment by kujason** [comment]
The performance will depend on several factors such as the sparsity after projection into the image frame, how much of the scene structure is available in the LiDAR points, and what sort of results you are looking for (e.g. [evaluation metrics and/or structure preservation](https://www.kujason.com/notes/depth-completion.html)). As the sparsity pattern will be different for a 16 beam Velodyne, you may need to experiment with the kernel sizes or shapes to get better results. I have tested this with a 32-beam LiDAR and with some minor adjustments, it gives reasonable results.

**Comment by zhouzheyuan** [comment]
@kujason  Hi! how is your setting for a 32-beam LiDAR?  I have used the default setting but the result doesn't feel right.

> I have tested this with a 32-beam LiDAR and with some minor adjustments, it gives reasonable results.

**Comment by kujason** [comment]
@SirJamie I can't recall the exact settings I used, but I think I simply adjusted the initial dilation kernel to be a taller diamond shape in order to account for the larger gap between the LiDAR rings. You may need to do some experimentation to find a good result with your own setup.
